<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Commission Invoice #{{ $commission->id }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; font-weight: bold; }
        .header h2 { font-size: 14px; }
        .section { margin-bottom: 15px; }
        .section-title { font-weight: bold; font-size: 14px; margin-bottom: 5px; border-bottom: 1px solid #333; padding-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 6px 8px; text-align: left; }
        .signatures { margin-top: 40px; }
        .signatures table td { width: 33%; text-align: center; padding-top: 40px; }
        .footer { position: fixed; bottom: 10px; text-align: center; font-size: 10px; color: #666; width: 100%; }
        .amount-words { font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $settings['business_name'] ?? config('app.name') }}</h1>
        <h2>{{ $settings['business_address'] ?? '' }}</h2>
        <p>{{ $settings['business_phone'] ?? '' }} | {{ $settings['business_email'] ?? '' }}</p>
        <hr>
        <h1 style="font-size: 22px;">COMMISSION INVOICE</h1>
        <p>Invoice No: {{ $commission->id }} | Date: {{ now()->format('d M Y') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Agent Details</div>
        <table>
            <tr><th style="width: 160px;">Agent Name</th><td>{{ $commission->agent->name ?? 'N/A' }}</td></tr>
            <tr><th>CNIC</th><td>{{ $commission->agent->cnic ?? 'N/A' }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Deal Details</div>
        <table>
            <tr><th style="width: 160px;">Deal No</th><td>{{ $commission->deal->deal_number ?? 'N/A' }}</td></tr>
            <tr><th>Property</th><td>{{ $commission->deal->property->title ?? 'N/A' }}</td></tr>
            <tr><th>Sale Price</th><td>Rs. {{ number_format($commission->deal->sale_price ?? 0, 2) }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Commission Details</div>
        <table>
            <tr><th style="width: 160px;">Commission Rate</th><td>{{ $commission->percentage ?? 0 }}%</td></tr>
            <tr><th>Commission Amount</th><td>Rs. {{ number_format($commission->amount, 2) }}</td></tr>
            <tr><th>Amount in Words</th><td class="amount-words">Rs. {{ number_format($commission->amount, 2) }} only</td></tr>
            <tr><th>Status</th><td>{{ ucfirst($commission->status ?? 'pending') }}</td></tr>
            <tr><th>Payment Timeline</th><td>As per agreement</td></tr>
        </table>
    </div>

    <div class="signatures">
        <div class="section-title">Signatures</div>
        <table>
            <tr>
                <td><strong>Agent</strong><br>_________________________</td>
                <td><strong>Agency Representative</strong><br>_________________________</td>
                <td></td>
            </tr>
        </table>
    </div>

    <div class="footer">
        This invoice is computer-generated and does not require a physical signature.<br>
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
