<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Possession Letter {{ $deal->deal_number }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; font-weight: bold; }
        .header h2 { font-size: 14px; }
        .section { margin-bottom: 15px; }
        .section-title { font-weight: bold; font-size: 14px; margin-bottom: 5px; border-bottom: 1px solid #333; padding-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 6px 8px; text-align: left; }
        .signatures { margin-top: 40px; }
        .signatures table td { width: 33%; text-align: center; padding-top: 40px; }
        .footer { position: fixed; bottom: 10px; text-align: center; font-size: 10px; color: #666; width: 100%; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $settings['business_name'] ?? config('app.name') }}</h1>
        <h2>{{ $settings['business_address'] ?? '' }}</h2>
        <p>{{ $settings['business_phone'] ?? '' }} | {{ $settings['business_email'] ?? '' }}</p>
        <hr>
        <h1 style="font-size: 22px;">POSSESSION LETTER</h1>
        <p>Date: {{ $deal->possession_date ? $deal->possession_date->format('d M Y') : now()->format('d M Y') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Property Details</div>
        <table>
            <tr><th style="width: 140px;">Title</th><td>{{ $deal->property->title ?? 'N/A' }}</td></tr>
            <tr><th>Location</th><td>{{ $deal->property->location_address ?? 'N/A' }}</td></tr>
            <tr><th>City</th><td>{{ $deal->property->city ?? 'N/A' }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Certification</div>
        <p>This is to certify that possession of the above property has been handed over by:</p>
        <p><strong>SELLER:</strong> {{ $deal->seller->name ?? 'N/A' }}</p>
        <p><strong>TO BUYER:</strong> {{ $deal->buyer->name ?? 'N/A' }}</p>
        <p>All dues have been cleared and the property is in satisfactory condition.</p>
    </div>

    <div class="section">
        <div class="section-title">Handover Details</div>
        <table>
            <tr><th style="width: 180px;">Keys Handed Over</th><td>________ sets</td></tr>
            <tr><th>Electric Meter Reading</th><td>________</td></tr>
            <tr><th>Gas Meter Reading</th><td>________</td></tr>
            <tr><th>Water Meter Reading</th><td>________</td></tr>
        </table>
    </div>

    <div class="signatures">
        <div class="section-title">Signatures</div>
        <table>
            <tr>
                <td><strong>Seller</strong><br>_________________________</td>
                <td><strong>Buyer</strong><br>_________________________</td>
                <td><strong>Agent</strong><br>_________________________</td>
            </tr>
            <tr>
                <td><strong>Witness</strong><br>_________________________</td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>

    <div class="footer">
        This letter is computer-generated and does not require a physical signature.<br>
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
