<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Token Receipt {{ $deal->deal_number }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 18px; font-weight: bold; }
        .header h2 { font-size: 14px; }
        .section { margin-bottom: 15px; }
        .section-title { font-weight: bold; font-size: 14px; margin-bottom: 5px; border-bottom: 1px solid #333; padding-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 6px 8px; text-align: left; }
        .signatures { margin-top: 40px; }
        .signatures table td { width: 33%; text-align: center; padding-top: 40px; }
        .footer { position: fixed; bottom: 10px; text-align: center; font-size: 10px; color: #666; width: 100%; }
        .amount-words { font-style: italic; }
        .terms { margin-top: 15px; }
        .terms ol { padding-left: 20px; }
        .terms li { margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $settings['business_name'] ?? config('app.name') }}</h1>
        <h2>{{ $settings['business_address'] ?? '' }}</h2>
        <p>{{ $settings['business_phone'] ?? '' }} | {{ $settings['business_email'] ?? '' }}</p>
        <hr>
        <h1 style="font-size: 22px;">TOKEN RECEIPT (Bayana)</h1>
        <p>Receipt No: {{ $deal->deal_number }}-TKN | Date: {{ $token->received_date ? $token->received_date->format('d M Y') : now()->format('d M Y') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Receipt Details</div>
        <table>
            <tr><th style="width: 160px;">Received From</th><td>{{ $deal->buyer->name ?? 'N/A' }}</td></tr>
            <tr><th>Property</th><td>{{ $deal->property->title ?? 'N/A' }}, {{ $deal->property->location_address ?? '' }}</td></tr>
            <tr><th>Sale Price</th><td>Rs. {{ number_format($deal->sale_price, 2) }}</td></tr>
            <tr><th>Token Amount</th><td>Rs. {{ number_format($token->amount, 2) }}</td></tr>
            <tr><th>Amount in Words</th><td class="amount-words">Rs. {{ number_format($token->amount, 2) }} only</td></tr>
            <tr><th>Payment Method</th><td>{{ $token->payment_method ?? 'N/A' }}</td></tr>
            <tr><th>Reference No</th><td>{{ $token->reference_no ?? 'N/A' }}</td></tr>
        </table>
    </div>

    <div class="section terms">
        <div class="section-title">Terms</div>
        <ol>
            <li>This token amount is part of the total sale consideration.</li>
            <li>If the Buyer backs out, this amount may be forfeited.</li>
            <li>If the Seller backs out, double the amount shall be refunded to the Buyer.</li>
            <li>Balance payment shall be made as per agreement.</li>
        </ol>
    </div>

    <div class="signatures">
        <div class="section-title">Signatures</div>
        <table>
            <tr>
                <td><strong>Receiver (Seller/Agent)</strong><br>_________________________</td>
                <td><strong>Payer (Buyer)</strong><br>_________________________</td>
                <td><strong>Witness</strong><br>_________________________</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        This receipt is computer-generated and does not require a physical signature.<br>
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
