<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotation {{ $quotation->quote_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { width: 100%; margin-bottom: 30px; }
        .header-left { float: left; width: 50%; }
        .header-right { float: right; width: 50%; text-align: right; }
        .clearfix::after { content: ""; display: table; clear: both; }
        h2 { margin: 0 0 5px 0; font-size: 18px; }
        h3 { margin: 0 0 5px 0; font-size: 16px; }
        .text-muted { color: #888; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; font-weight: 600; }
        .text-end { text-align: right; }
        .text-center { text-align: center; }
        .totals { float: right; width: 250px; }
        .totals td { border: none; padding: 4px 10px; }
        .totals .grand-total td { font-weight: bold; font-size: 14px; border-top: 2px solid #333; padding-top: 8px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; color: #888; font-size: 10px; border-top: 1px solid #eee; padding-top: 10px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header clearfix">
        <div class="header-left">
            <h2>{{ $settings['business_name'] ?? config('app.name') }}</h2>
            <p class="text-muted">{{ $settings['business_address'] ?? '' }}</p>
            <p class="text-muted">{{ $settings['business_email'] ?? '' }}</p>
            <p class="text-muted">{{ $settings['business_phone'] ?? '' }}</p>
        </div>
        <div class="header-right">
            <h3>QUOTATION</h3>
            <p class="text-muted"># {{ $quotation->quote_number }}</p>
            <p class="text-muted">Date: {{ $quotation->created_at->format('d M Y') }}</p>
            @if($quotation->expiry_date)
                <p class="text-muted">Expiry: {{ $quotation->expiry_date->format('d M Y') }}</p>
            @endif
        </div>
    </div>

    <div style="margin-bottom: 20px;">
        <strong>Bill To:</strong><br>
        {{ $quotation->client->name }}<br>
        @if($quotation->client->company){{ $quotation->client->company }}<br>@endif
        @if($quotation->client->address){{ $quotation->client->address }}<br>@endif
        {{ $quotation->client->email }}<br>
        {{ $quotation->client->phone }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th class="text-center">Qty</th>
                <th class="text-center">Unit</th>
                <th class="text-end">Price</th>
                <th class="text-end">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotation->items as $item)
            <tr>
                <td>
                    <strong>{{ $item->item_name }}</strong>
                    @if($item->description)<br><small class="text-muted">{{ $item->description }}</small>@endif
                </td>
                <td class="text-center">{{ $item->quantity }}</td>
                <td class="text-center">{{ $item->unit ?? '-' }}</td>
                <td class="text-end">{{ number_format($item->unit_price, 2) }}</td>
                <td class="text-end">{{ number_format($item->line_total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="clearfix">
        <div class="totals">
            <table>
                <tr>
                    <td>Subtotal:</td>
                    <td class="text-end">{{ number_format($quotation->subtotal, 2) }}</td>
                </tr>
                <tr>
                    <td>{{ $settings['tax_label'] ?? 'GST' }} ({{ $quotation->tax_rate }}%):</td>
                    <td class="text-end">{{ number_format($quotation->tax_amount, 2) }}</td>
                </tr>
                <tr class="grand-total">
                    <td>Total:</td>
                    <td class="text-end">{{ number_format($quotation->total, 2) }}</td>
                </tr>
            </table>
        </div>
    </div>

    @if($quotation->notes)
    <div style="margin-top: 40px;">
        <strong>Notes:</strong>
        <p class="text-muted">{{ $quotation->notes }}</p>
    </div>
    @endif

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
